spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
    check-template: true
    check-template-location: true
    enabled: true

  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gd?characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /mall


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: gd.mall.po